batch_size: 4096
checkpoint_name: checkpoints/histogram_js_max50_random/version_12/epoch=422-step=4653.ckpt
ds_same_dtmc_fraction: 0.01
ds_size: 100000
dtmc_folder: ../data/max50_random_2/ready/dtmcs
dtmc_max_size: 50
hidden_size: 4500
input_size: 2500
label_folder: ../data/max50_random_2/ready/labels
label_type: HISTOGRAM_JS
loss_fn: contrastive_loss
lr: 0.001
margin: 1.0
max_dtmc_size: 50
num_workers: 8
seed: 0
test_size: 1
train_size: 0
val_size: 0
