batch_size: 1000
ds_same_dtmc_fraction: 0.2
ds_size: 1000
dtmc_folder: ../data/only50_random_49-50full/ready/dtmcs
dtmc_max_size: 50
hidden_size: 4500
input_size: 2500
label_folder: ../data/only50_random_49-50full/ready/labels
label_type: SPECTRAL_DISTANCE
loss_fn: contrastive_loss
lr: 0.001
margin: 1.0
max_dtmc_size: 50
num_workers: 8
seed: 2
test_size: 0.1
train_size: 0.8
val_size: 0.1
